#!/bin/sh

# Usage:
# 	makea [-r plan9root] [ed files]

orig=$HOME/plan9
if [ $# -gt 0 ]; then
	if [ $1 == "-r" ]; then
		shift
		orig=$1
		shift
	fi
fi
orig=$orig/sys/src/9

if [ ! -d $orig ]; then
	echo "Error: $orig is not a valid Plan9 root" 1>&2
	exit 1
fi

files=a/*.ed
if [ $# -gt 0 ]; then
	files=$*
fi
hfiles=a/*.h
for f in $files; do
	name=`echo $f | sed 's,.*/,,;s,\.ed,,'`
	ofile=`(ls $orig/port/$name.[ch] || ls $orig/pc/$name.[ch]) 2>/dev/null`
	dfile=`echo $ofile | sed 's,.*/,a/,'`
	echo -e ",p\nq" | cat $f - | ed -s $ofile | sed -r '
/^#include/s,../port/,,
/^#include[ 	]+<('`echo $hfiles | sed 's,a/,,g; s/\./\\./g; s/ /|/g'`')>/s,[<>],",g
	' > $dfile
done
