#!/bin/sh

# Find the -o or -c argument.
iscc=0
next=0
out=a.out
flags=""
for i
do
	case "$next" in
	1)
		out="$i"
		next=0
		;;
	esac
	case "$i" in
	-o)
		next=1
		;;
	-c)
		iscc=1
		flags="-ggdb -mfp-ret-in-387"
		;;
	esac
done

case "$out" in
/*)
	;;
*)
	out="`pwd`/$out"
	;;
esac

# Run regular gcc
vx32-gcc $flags "$@" || exit $?

case "$iscc" in
1)
	exit 0
esac

# Rename output to _output
uout="`echo $out | sed 's!.*/!&_!'`"
mv $out $uout

# Write new output file 
cat >$out <<EOF
#!/bin/sh
exec vxrun "$uout" "\$@"
EOF
chmod +x $out
exit 0
