/* This file is normally generated by libogg's configure script,
 * but here we just hard-code it for vx32. */
#ifndef __CONFIG_TYPES_H__
#define __CONFIG_TYPES_H__

typedef signed short		ogg_int16_t;
typedef unsigned short		ogg_uint16_t;
typedef signed int		ogg_int32_t;
typedef unsigned int		ogg_uint32_t;
typedef signed long long	ogg_int64_t;

#endif
