ROOT=''
SRC9=$ROOT/sys/src/9
CWD=`{pwd}

EDFILES=`{ls *.ed}
SRCFILES=${EDFILES:%.ed=%}

boot.9: files
	bind -bc $CWD $SRC9/boot
	cd $SRC9/pc
	mk bootpcf.out 'CONF=pcf' &&
		mv bootpcf.out $CWD/boot.9
	unmount $CWD $SRC9/boot
	unmount $SRC9/boot $SRC9/boot

files:V: $SRCFILES

([^/]+)\.([ch]):R: \1.\2.ed \1.\2.orig
	{	cat $stem1.$stem2.ed
		echo w $stem1.$stem2
	} | ed - $stem1.$stem2.orig

%.orig: $SRC9/boot/%
	cp $SRC9/boot/$stem $stem.orig

clean:V:
	rm -f boot.9 libboot.a8 *.[ch] *.orig
