\" # Generate html (uses p9p)
\" # sed -n 's/\\" //p' 9vx.1 | 9 rc > 9vx.html
\" troff -manhtml 9vx.1 | troff2html | sed '
\" 	s/Plan 9 man page/Plan 9 VX man page/
\" 	s,9VX,<a href="http://bytebucket.org/yiyus/vx32/wiki/">&</a>,g
\" '
.TH 9VX 1
.SH NAME
9vx, 9vx-tap \- Plan9 port to the virtual execution environment vx32
.SH SYNOPSIS
.B 9vx
[
.I -gt
]
[
.I -f inifile | var=value ...
]
[
.I -i initarg
]
[
.I -r localroot
]
[
.I -u user
]
.SH DESCRIPTION
Plan 9 VX (or 9vx for short) is a port of the Plan 9 operating system to
run on top of commodity operating systems, allowing the use of both Plan
9 and the host system simultaneously. To run user programs, 9vx creates
an appropriate address space in a window within its own address space
and invokes vx32 to simulate user mode execution.
.PP
9vx configuration is determined by
.I var=value
pairs read from its argument list or from one or more
files specified as 
.I –f inifile
(a file name
.L -
means the standard input). The rules are the same than for plan9.ini(8)
files, with the addition that values between quotes in rc(1) style
can span multiple lines.
.PP
The following variables are understood by 9vx:
.PD
.TP
.B cpulimit
Maximum cpu usage in percentage. A value of 0 (by default) means that
there is no limit
.TP
.B memsize
Memory size in Mb (256 by default)
.TP
.B canopenpath
Limit access to the host file system, accessible from inside 9vx as
#Z. Only the host files whose path begins with canopenpath can be opened
(/ by default)
.TP
.B etherx
setup a virtual ethernet device. Possible device types are tap and
pcap. Parameters can be dev and addr, with defaults dev=/dev/tap0
for tap and dev= for pcap (will look for the first one available) and
addr=00:00:09:00:00:0x in both cases. If no device is configured the
network stack of the host system is used
.TP
.B initarg
set init=/386/init -t initarg quoting initarg as needed
.TP
.B localroot
set nobootprompt=local!#Z/localroot after converting localroot to an
absolute path in the host.
.TP
.B user
sets user name, the host system user is used by default
.PP
Additional
.I var=value
pairs are used to set environment variables before control is passed
to boot(8). Some variables can be set directly using flags in the
command line:
.I -i
sets
.I initargs
,
.I -r
sets
.I localroot
and
.I -u
sets
.I user.
If
.I -t
is given the current tty or the standard input/output will be used as
the system console. With
.I -g
the gui will not be started.
.SS Booting 9vx
When started, 9vx will run a modified version of boot(8) which accepts
additional file system locations for the local boot method: local
directories, fossil and kfs partitions (possibly in a local file),
iso images and bz2 files (a compressed file system /boot/rootfs.bz2 is
included in the 9vx executable).
.SS Running 9vx as a cpu server
To run 9vx as a cpu server is recommended to add a cpurc file in
/cfg/vx32/, see cpurc(8). An example is included with 9vx. This file
will be used if the
.I service
environment variable is set to
.I cpu
or if the
.I -ic
option is given in the command line.
.SS Exiting 9vx
Reboot signals terminate 9vx execution. In particular, the reboot command
will exit printing its arguments to starndard error.
.SH BUGS
The pcap ethernet device is not compiled by default (fails without
pcap.h). To compile it, set PLAN9PCAP to etherpcap in the Makefrag file
and recompile.
.P
The menu system of plan9.ini(8) is not supported in
.I 9vx.ini
files.
.P
Debugging flags are undocumented (
.I -1ABFKLMPSUX
)
.P
.I 9vx
is not so stable as native Plan9 systems.
.SH "SEE ALSO"
.br
Bryan Ford and Russ Cox,
``Vx32: Lightweight User-level Sandboxing on the x86'
